//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KFlearning.Go.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KFlearning.Go.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KFlearning Go merupakan aplikasi untuk membimbing kamu belajar mengenai data science dengan cara membaca teori dan melakukan praktik koding menggunakan Python pada Google Colab.
        ///
        ///Selain data science, kamu juga bisa mendapatkan berbagai info menarik dan artikel teknologi lainnya pada blog kami!.
        /// </summary>
        internal static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amalia Sabrina.
        /// </summary>
        internal static string AboutNameAmal {
            get {
                return ResourceManager.GetString("AboutNameAmal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fahmi Noor Fiqri.
        /// </summary>
        internal static string AboutNameFahmi {
            get {
                return ResourceManager.GetString("AboutNameFahmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI/UX Designer.
        /// </summary>
        internal static string AboutRoleDesigner {
            get {
                return ResourceManager.GetString("AboutRoleDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# Developer.
        /// </summary>
        internal static string AboutRoleDeveloper {
            get {
                return ResourceManager.GetString("AboutRoleDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentang KFlearning Go.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baca apa hari ini?.
        /// </summary>
        internal static string BlogHeading {
            get {
                return ResourceManager.GetString("BlogHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore artikel dan informasi teknologi disini!.
        /// </summary>
        internal static string BlogSubheading {
            get {
                return ResourceManager.GetString("BlogSubheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        internal static string BlogTitle {
            get {
                return ResourceManager.GetString("BlogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode Membaca.
        /// </summary>
        internal static string BrowserTitle {
            get {
                return ResourceManager.GetString("BrowserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beranda.
        /// </summary>
        internal static string DashboardTitle {
            get {
                return ResourceManager.GetString("DashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navbar.
        /// </summary>
        internal static string NavbarTitle {
            get {
                return ResourceManager.GetString("NavbarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        internal static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belajar koding interaktif lebih mudah dan cepat dengan #KFLearningGo.
        /// </summary>
        internal static string SplashPromo {
            get {
                return ResourceManager.GetString("SplashPromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mau belajar apa?.
        /// </summary>
        internal static string TutorialHeading {
            get {
                return ResourceManager.GetString("TutorialHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gausah pusing! Yuk cari tahu tutorial disini..
        /// </summary>
        internal static string TutorialSubheading {
            get {
                return ResourceManager.GetString("TutorialSubheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        internal static string TutorialTitle {
            get {
                return ResourceManager.GetString("TutorialTitle", resourceCulture);
            }
        }
    }
}
